name: downloader_plugin
description: Internal downloader plugin
version: 0.0.1
homepage:

environment:
  sdk: '>=2.11.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  
  localstore: ^1.3.5
  path: ^1.8.1
  path_provider: ^2.0.2

  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:

flutter:
  plugin:
    platforms:
      android:
        package: com.example.downloader_plugin
        pluginClass: DownloaderPlugin
      ios:
        pluginClass: DownloaderPlugin
